# Generated by Django 5.1.3 on 2024-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepartmentApp', '0002_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
